Added recent measures to src/MLJ.jl
alan-turing-institute/MLJ.jl pull request #887
Opened 2022-01-08 05:12 UTC by sayantan1410

Fix #880 
Sorry, I tried to do it in the optimum way but as I am new to the repository and also this is my first PR to this repository, so I was little bit scared.  Once get a little bit more familiar to the codebase, I wish to come back to it. 
let me know if I made any mistake. 
@ablaom

2022-01-09 20:59 UTC, ablaom commented on src/MLJ.jl
> +    MAPE, MeanAbsoluteProportionalError, log_cosh_loss, LogCosh, LogCoshLoss, Rsquared, rsq, rsquared
This line is a bit long. You could start a new one. We try to to follow [BlueStyle](https://github.com/invenia/BlueStyle).

2022-01-09 21:00 UTC, ablaom requested changes
@sayantan1410 Thank you very much for this. 

Yes, that's a good idea to make a simple PR first.

Just the minor formatting comment and othewise good.

2022-01-10 10:30 UTC, sayantan1410 commented
Sure I will make the change ASAP 
Thank you @ablaom

2022-01-14 12:26 UTC, sayantan1410 commented
@ablaom just mentioning you here, incase you haven't noticed the changes.

2022-01-17 21:32 UTC, ablaom commented
Thanks for patience. Just back from leave.

2022-01-17 21:33 UTC, merged

2022-01-20 10:10 UTC, sayantan1410 commented
That's all right, hope you had a great leave and thanks for merging the PR.